import Day03.common
import Day03.groups
import Day03.idPriorityMap
import Day03.input
import Day03.compartments

fun main() {

    val answer1 = input.lines().map { compartments(it) }.sumOf { idPriorityMap.getValue(it.common()) }
    println(answer1) // 8401

    val answer2 = groups(input).sumOf { idPriorityMap.getValue(it.common()) }
    println(answer2) // 2641
}

object Day03 {

    val idPriorityMap = (generate('a', 'z', 1) + generate('A', 'Z', 27)).toMap()

    fun compartments(items: String): List<String> =
        (items.length / 2).let { middle -> listOf(items.take(middle), items.takeLast(middle)) }

    fun groups(input: String): List<List<String>> = input.lines().chunked(3)

    fun List<String>.common(): Char =
        map { it.toSet() }.fold(first().toSet()) { acc, next -> acc.intersect(next) }.first()

    private fun generate(start: Char, end: Char, startPriority: Int): List<Pair<Char, Int>> =
        generateSequence(start to startPriority) { (id, priority) ->
            if (id == end) null else id.inc() to priority.inc()
        }.toList()

    val input = """
        lflZfgnSnlmmlgGfjGthQPtLNsQhvbHLLpSS
        zrCVDVFMJTCTcCJMwCThWbtbpbWpPbtbHPLQssLsHP
        rBFcrwFzFwwVDcDrzTzJfnRGjllBdGZnnZfhqmdn
        FjpnFRDmbRtnbJrFJmSTsGShWVhGqGVVsmqs
        ZwPvNPdzNZwfzBNLdNNNNcLvhnQhqMTVsTGSWSqGqTdVWhMT
        vgLZHfvLffNLPbggnrbFpJnCbC
        hzJzGjGfqmGtDQtDSvVV
        plpcMBNBcCTlTgCMbvtrsSVsVJDJlrwDQr
        McHBMMcTTHgJnWqnRqjzZnnRzR
        ppvsGZhDGprrSjSllwfZ
        TTFMMFJMgMHmHmdqdSvNqlSSSNJv
        mgBPHTRWFRVcpvsVttppbv
        ZZDssfMDMtqqppZLLJzmzSTwNJplTSgpgm
        BdCRRHFRbccWWBvBHCdcJVngNVSvTgVNzgNNVmnz
        QHFFrBdcGtqPmmQh
        qLvQFRgLSSNgqQvRrqLTQvLttwDBFWDwjwFttDdlBBwBwM
        nbsmZnbmHbZVCGPVmHWtwlStBDtwBMtwWHMj
        CnCbhGCPpPCSnZmrgRNRqNRrLNgrzh
        vgLWWHRNLnWwLggWzwLFFzMmBMRMhMhTbhsmmsbbmQTm
        rScpJJDDpjtSDPPPJDpjqPCHBBtlTdblmmlhBsMMmTsbmtsl
        GHZHCPprSSwgvWNVwVZv
        dMrCMJMqvtdFwcjczjQzThtm
        gGbLblLpZlHvllQhlQwcjT
        GHRWvPRbPHPRvNGbvdRBqdqBBfRqBqnrfF
        VsHcljlbhmHbHHlcjVcVShJSCdJCfMrMMQDfRNFCfMRGfNrQ
        tGtvLtpgBTGvDMMRdMMgdCNM
        pnGnGqGtvtzTLjWqmSSjHhWhWs
        NJTDntDNDVjNnjBfjjjcCZCZcVqCSCLqcSScCc
        zvhgRgQvvdllgQbHghlvHrRHSScBCRqqwCLGqSMCZCGGGqMZ
        pvvrHzdgvlgzQphQsDFmnsNTTtjfjJJmPB
        ScnSZSZZlmjmHjjWHHWZftJVJpppwtVVnLJtnptnwt
        CFFlQBbbPQqrBwJrJJrGJD
        PgTqRddFzgdRPFFbFgqQFgsSjfHWfSHmSMWcjZlmZmjTZM
        lzBRtctbnBRBRBBWnDnDWjlLVvwGMrvwrHHQHGmDvHQvHGrV
        FsTgFCTSgsCNspzhCGMfTHQVwVMfMmMmrH
        hSdSFgghhqpRbLqjntqnPz
        DCDnNGFFDQdQmVDNdFVNFccpJLHWSvPLrvvvPtGGhSttLv
        sBgTzzZqrBlfljslWBhvHSvPBhSBJSSL
        lRlTgMzlzrwRrnmbCMCFnNVMnc
        MJQJMJHBrsdrHwts
        dbbSVGgbjVqGTVfqddCTpmWWcprgNgWmcWwWswpN
        LPdGGdVGPCVdLBlBMlDRRRMD
        vdcwZLTdTFFRDHVgmpppMmqZ
        jGPzCnQPjlsDVqDpqDHbgP
        BjWJrlGQQzrCzBzlzBCGBznzwNRNcwLJdwTJFTHRSTvtLcNN
        ngrgqTjJJZnjFJpnqnnVTLzBbbHbLQdLHLHbrdHdHG
        lNcltCCtvftfWssPbMQdMBzhbbcBDLdh
        PRtWsQCmWsmSsCNCSvCSWlspwgqjqmqjTpnJZwnZVpFwgq
        PjWjGDCjmrmWPNmvWDWFmgCNfVJRLfJRfLDLJQlfHplpRbfR
        MtZMtcSbccZshTtQTVVTpzHlLRRQLV
        cZhbwMnwqsqnhnqtMBnvNFrnGPNPPmgPGCgW
        WBjWjWjqZwQJnJZCZZbf
        StHSDRPHHcTrTrJpLCCMbrqnJn
        RvTTvGqcqTFvSvSRDHvRjlhgWBWBdhjwjGgNjhlj
        FSbCqcFsbCPtrcrqhCScbshMjHDGGWBLHBnjGLPBHGGBGnHj
        flQdlsgQgGnQHBHjDn
        vllgRZdmvsvpgdwZgzJdwRmprqccSFcSShJbTSttqMCrCCch
        GwwgCtvHgwcHVVDqpWdfnqVv
        sllBsSNBjSrLfqhLgjfqhL
        ZbQbZQzgQQPSblBggNQRHGZHHCmwmHFGGcwtJm
        CmGVGBTVTmmTWTNLLCVgCSFvDQppQQDDnDQDJpMggfnQft
        RrtdqtldPbHzRbnjRfQZjJfMDnMj
        wcwhccqrdrrlFmLGCwCtSwtL
        pzZznZphZnpcNWSwGwVVPzrPrG
        lgFllLLltgbDsrBCwrjWGmwmtw
        MgJbDLlMQRJccchrhc
        wbbjzZhdGDwLzZSBWqqHmZgssCWqFtMZ
        VRJccfvPlTTlQlHQCWQhMMhCCHqQ
        RlVfVJcPTVTfvvvJfNJVlcBjGjwhSLdBNGGnjLLBwzGb
        bvpqHMVTTpZnqnWRQQQw
        tfhFFdSFggfhbldhhZcnRscRcQmnRs
        DPzgFJzFLfFbFSgPFgdPglMHpvBpHTCMGpjvMMpLvvNG
        JggGLQgQpLpSPRJgGPSnGlFTDBjjRFvRjtBFjWvFjqRj
        cmHhZcMHcWjrTBjrvm
        dbHwdNNHhwTNThZHdlwQJJwngpgnJGnSPw
        DbZjVfjVLhZDLpWPHpMZPmmGNp
        lFcJJGcFqnBFqwJCHHMmNHPsdCNp
        BlwccRQtBwBrwLGbGhGggzLgzR
        RBhZPjlWqgbNbgGLBr
        MzSmSzpFdHwpswzzHnzjnvLCbgtrtLGLbJLLJNtJtbwJ
        MsSHdmMdpFfmFjpfcPWRhRVZfWQThZ
        mqmssPCFhhsJccVg
        FTttfwdjjHznJgfngpnc
        dNFTjQNRtRNQldRNrRdHMRrlPZqCGlGBCqqZmmbPqDmDCmGW
        ZJVRRZZJRcvmPhCJrvhm
        PPWQDTfWbnnstlCGvjGrWMGMvr
        TbbwddndsnsfDpwFqZFVHBVPqc
        tFmpJmgJJgmFDWgRgFrrlGSltSQvZChMtCMM
        TLcZHsjLVNBwGQCCGlsCShvh
        nqNdwwccBwVLwjjDznZzppbgzFZfDF
        qsTqCCCszjlqTssBShlQSSZFgZZhgB
        LDPmVgDDJdLPrPgLgPZSFZQfhQGGBQJcSFJS
        mvmVbVvtggVtvgdLVvtmptCsNTtjRnpRTTjpsqCp
        BdNPLnmFvLFNgnmBmnFGnwSZZZWwqWgqjwWssTHWSS
        bJhMzhbVMbDCcVpZtjHMqTMwtttSjH
        hzclfCppVqQfbzQVbpzPQLNFBdrvdNGGBnmrmP
        nLVLzBDJCCHqdLncqVJgSsDlGsbssmvvvbvbff
        jMNHFWNTZZNwMPrPWrrPMMrrvSllbgsllfgbgvQsvGmglZbv
        RjPjrjRPtNrwHhBtncCJtJtL
        jbhhjhNjvqNbmjMjqhtCFdmPFdlzJzfFfJQJfR
        GBBZWrZWgpSsnSngrrSgHzFzFFdClzfFQFlRZftQPR
        TrGTrGWHpHWGHWVWsngprHpLbLLVvcqMcNbVNLhwVNbtNb
        sQDvDmDLQFDRsdchzhBczLhhPhVz
        MbGGMjjGZSjvfHvHSbfwBqcPnqqcPVhPNnqnzjcn
        ZwMMHrWvSHbfJfTrbJwSMMfMsQDtsFRptlpdCRpWmptQDRmC
        TwMHdcTznLqzTrHdzzzHTdgMRQWRhJhNjjvgQvQQWNjl
        tbfsVbDCVSSDtSPQJWPvRNhQtghN
        FVGBpGCVFCbfCbVbZCSHqmwqcqLcdHJGwHqqTd
        lTlGfjLGwHNMggscsDRwsC
        MrFtrzZZPZrtVQtnrrFdQhhDPDSphgDRhDcsCCgWpW
        ZJmJVzVVJFHfGbqJGMLv
        zsFZVjzlHPfTzGfLGt
        mdrrmdMMcBcmNqNbPqfRDLPWPlqTWD
        BNQhmmrBrQghgSmNBQQSmvwssjZZSJHljJFFHZJvZV
        rLZCsZdMJfdNCsfZMrLdFmssnwgTRQgBBwgRwcngTNVRVQjV
        StqDHlStDPgRTqcwjT
        GlDGDhbpHhvSHWlzbWlhpzhJdrFLrCLmvdmFZsmJJjJfdv
        pJHJMJsJjSMFdHhszFvMhlmmGNlSmmBGllWmVlwcTw
        ZqZRDrZCZDtPDPDrCngrnnPQGVmGHVBWGWtGmWVwVlmTlGNl
        ZQPgRqrrQPqLnrLMvLphHdvdjpJddb
        NwbBjljFbcjtTcccqW
        RHZrPHPpNgZTzTqc
        sfrPdmPdpsmPPPrfQPVGlwGVBwbGVnFlNQCG
        hQdNTlzhdTvrhdnTBqcWBLsBHgWQgBPg
        zwzRDbDfqZBLHDLB
        wFbFmjjRzfmjGGMGMfmJwwGCCnvNhpvSCNnrvJvCprnnSp
        zshNNJbwGFJfGJzzzNRnHGnCnRHcRPgTmPmn
        LMDVtZLStrrZClBrVDllLSBWRPTPPRRPmgWPVmPTPHTWgR
        SDSqLMlrtLlLtrBqBdlMZjvffCNzwvhjvvzhdfNhvf
        SLQmGBmhLSLQTBGBGwdwpJjwwQjwcVpJZJ
        sNrWrWPNbHghrbgnNNzbWbFWdZpMpzVpdMZMzMMVZcwwJdwd
        frrPNNWshWhhHDvDGDRSBSRvttqv
        FJqpgvhJJRjFjZTqDsMHrzwjsSsSszMrMm
        PPPQWGtnbbfBmPsFswwsMrcc
        QfBtbldtWQfbWbnfGlFqZppvpFZZLhFlpq
        ZqSMZHHCMpHTZTWmFTFZPZQJBgVGVJQvVVSDBvBtcBBG
        RNsndwsNjsbsgGCgjQBttcBg
        NRszRRNzLNNNwNfhCCrfdmTqFZllFFHFFpWhlTmWpq
        llbbzDmSspGRpHpzsldzRRsVtFBBFJMMVVFLTTTMVtLTDM
        cqgjqvNgvqCjQZqgGGnhMTnMJVLBLMtFhhVFWB
        PfGGvQrPCjvjZgGCCCZZZbSmmmHlRpprlHrHwssSRr
        mRmpFpWpfMMgLnmS
        CdCsqzdRzqStLjSqfMnL
        wQRHdTzCQbzCwsTrZBlFZGpVlpFGQD
        qnMTnTVSTPTHTHcMZMvVpmppmFmVzFLLFLlFpG
        gBjDsjRRwhDDghthwwWZwLmpmwWWLWLbGZ
        NhZtZtBgPTNJJNTS
        jLjjmpHvzvZrfzQjmfHHWrfbqblLsSlTsqsgqPJbPqVglb
        FBcCwDwtwgcgnCwcGchtJSsRqVRVJPPqDlbSDRPq
        MBhthFNtMGCwhcwnpQfWjNrQprpvzpgQ
        RfCnWfnhCbwHgWjzBgzB
        PsVqDsSTshsgszpsph
        DPDvTVtTShhSZhmqSvLlQJFnQJJZnbCnlCCZ
        pRRdJngltnwwvTNSWqWffqgBqD
        HQGcsdrjzMDDBfGMGG
        FLhsdbzCLLHjhntpVnRPRvZV
        gZNwQHHNRlGvhvhGRvRb
        dpSSBDrzdCfcSzfrzZrfCfMbthWWWPttDthvMFWvvvPj
        ZdpBpZCrssBJZfSJBzBdCTcnmQwmnVVlmqTQTTQlHLwNnN
        ssCpTttVVVpzZDVvRpCsRtDgWBWBBFBJvvJHMBghGghrMJ
        lwLmNNLwSblbmSQLfhJHZgHrHhhJJhHHmW
        QLSdbdPqndlNlLdSLNQncpRtRTcRVTPPZRCjVCcc
        wzzJclzcTThvWSSCqRlQSsNN
        rDpVjpVVDpsQSRDRfQmm
        GLbjrLpFbgLVLLgdbjVpchcFZhvBwJvtvtJcZwRB
        wPgZgLVMfWVTgmTZZZftJjtfjtJCcdpjdCqc
        zGGbQQnQGvBBhGQvvvBBSBvQdhdqqCpdddDmJlCcDjCtJdmJ
        HszzHBzQBSmGSwTWgswZPWTVgZ
        GDFvzCFdrszSdNJrFfjjfqZjRfsjpqmcwZ
        WbbVtVnBPWMgBLMBnQQnBQHcjfjpZRwqcwMfcNTZRqqNmT
        WQQnVVPHtggLghWWhHnPVQbvlJhSlrvJDlFGJDdDCzGNFF
        dVhTBjBHtTVqWRJZRqhJZQ
        brSDTbDfcCwDzfCSbwMQnlqCRJnMgWWnZngM
        DFwNSrwNwbDzbFTTFtjmBpVdGpHs
        dPQfdfTzDrFDmFDBgBFj
        RlJRclcswJRvnwPcpjbjbbCZjFjbBmsbFZ
        pqncGlcRJpHGpllGHhvPhRTHrQrttVVfrdQzfrTdftfV
        RCzTzRMTfCfRRDzRfhSmZZlCslBbZZBVtZBZsqBL
        nvvJPpdcFnPcWnFnVZvBqVlZMbZBNVlV
        FpWPMdjdPhSTmwfSjD
        NDJjNHLLNWjcLLWCLJLZjLDtRqqtgtMqgtqnRqnSRgggtZ
        BwrlfFwmQwhwfPBFhsBdFmbQggCgqQVtbRSqttqMngnp
        llPPwsPlGshBJGWJLcHvCzNv
        rBvTmwdTSbnrvVWsWVftGfJQGT
        gNRLLjlPRWnFVRFDFW
        lpCpPNZqZCdvdppnSnBr
        ShRdCrJgHClZJtZDGMMz
        LvqVVTTNbVPLQNFTnwwMtzFZGDDwmtnM
        VLbNvpPvTNVqVbbNpbVPGNLPrRWrcRCWdSrCjWSHcHSdWpCh
        tNmZnLSZPFLDnLTmhJMWczQdhmWhWH
        bGqbgrpsCsWhcChNQfJz
        vwlNbppsRGRRSSSDvjTjLZjZ
        zgMZhgfBtftSZQQmLHpSWH
        cdqcqnrJVGjjqPVjrPnfpJmsQHQQpsSsbsSDmm
        NNnrNqNlrNcPTlBvBvgggfMv
        llPrrLHBHCrRRBjrHCjBdrPmvJZzZgZbmgJlZmZhMhhmvh
        pNDstVtNtGFNSDFScQtfwzzFJwmJhgqzbMwqZJmh
        fpNsptGtQcTsSTccprddCWPrWdTRBMMCMd
        TTtDVqTsTcJFgbCqmbCq
        NWZQnllzfBFZPBGWQGzFPFRNNgHbHrrwbNrmCbggJRHR
        nBZjGFjMQBMPZnjfWjstpcctttvVtcTttMpL
        qphVCCwnHqhnRVznFwvLtBTLDTWZtwLWWS
        JmdlsdlsjfJfrtjTcvtctDZSSB
        rsmfPGbrPbPJfPmrsgMrdJdlFTHhFCqhNqVHnNHHCFznhphG
        JsWFMJJzrhSSdFdldmmdmdQc
        qLLgCVTgLbBvqsQPVdQGcRRmQmdc
        bBCBgCCDbLDqTvqqjpShHfzrzMfjtHHSHsfz
        nvFSBFlvvgQFFBzQnlQglmRRzqwsrrMJJMrsMqrfrwzf
        CjZNCNhLDNbPZZLZZhwVjpcfrqRhsdJqdsshRTTdqJrJ
        jNNDDppjpjDWNVLCVVDpGVVPBFtlSQFWvvQvSSQHSgwQnvtB
        WhrQWBRWwhzgmpnSpH
        LqMVsJVvFMJLJMsfNjsTJvCgFbSmzgpSHzmngHbGPCbm
        jvMjjtqVjTRnwZQwBWwt
        jfTWSGSTTWhgcngQfbtJfNzztBQBzz
        pVVwsdppRVPLVmPsVVHsjPLPzQdzBzQFzFBNNrJZZQBzbbFF
        VmsqHmjHmpvGDSWDvlclSl
        PNZfTFSFfTFGCHqqmbFm
        WjzRWrjVgnjzplrWWjJVppgGPGsgstmPCCtcmssQqGQt
        pzjzJVvnzJjWvpPlnVRVrvnlTDLNNhwfdNZLfMZLwLhTNvTw
        QFrQZMFVrVpVszzcNTdMRCCb
        SvljGmlvLfwLhLLLHlHdNzsRthhbbRccRCRNbC
        LfwlDmlvGBSjjlLLgpPpFJqgQndQgZBJ
        RBjPRHdjPfqQcfhcdv
        SngFcJZJlcnctSlhhsQvGsDGDsDnfs
        pSmFgSWNJFNtStrmNtpCCjPVcbjjHbcWTBHBHL
        vGjqCPqNPGFGNftLwmZwfQNTLp
        hrdBCSHcCJJcCBShJswmLQpLbbQZTLLJmmZp
        BdHHSzrBWdzchzzCcdzHddcDVWFnjPjllGggVlWljPFFFWPM
        hBtZZnpbhbPZJbnhDtPnpBtpfjfNNzrrCzjFzFzFTjfjjWzJ
        gHllMqRSmqcqMTdggMqHlcFzRrFQWNfvrRvzQrWjWvWf
        gwqlgHmmdsgwlwMHZtpsbBbtDBThbBht
        CsDLFFLFCvczsCsJrCrJJLRgbQQgmMmPbDDQbPnMgMmg
        VlwNBNVhjNVNWBwWjtbRMRZzPmQnfQMPnlZP
        VWWSSwGTwtwWWNVwwpqJJrcJGvzqCJCqJF
        wLwSSbzwCvddlvvlSj
        THnQnnHttcvpQzrZRllZ
        sTntBHTnVbPbgzsbgL
        FwHgrHvFQQwpHhNhTBLdpNNNLd
        fCGqCVtszfSslCSzSGsfCssjNTqLTdmjNLBLdnTTTMTjTg
        DccfslfgRSSVVzlcSVtzDRVHwQZFrwwvwFWbbbRRWwrFJb
        CwwWwwFNRpFFpZQHtsmfqbQDTQTTqb
        VcjzLjGjzGjGjVjLdzqmDqHrsmsqGRrHqGqH
        RjdVlgdnljlBnSgPCpNwwMWwMM
        tCCtqtbPGzsSQVzQTq
        mzMmHMpRsRQTsFFV
        DpzDwgdMzMLppNmNpDpfgrbhLcGtPrbtrbrbhnbBcC
        BvsQBBBLvDQGjDvSQLTvrHprHlRpVlVllgRbRbHPqq
        MMMMCpfJFZZMmCzwpVPCWRtHgqWgqClgtt
        FwzmfzhFFdFcpvSDSBDThs
        fQrGQbFFFrHHtlHPclzzPLvc
        mTnwpNCCqMqjmCThpTpSvvtBczstlLznvsztsPPP
        mCpTNhmmpCqCmjmpTjmLCpSJQZVfFVrDVfffFFgfgJQFdbgG
        GmWjRBSfttcGfRcSclVVJqsTMllsgJVMVZwV
        pPFNpfNCdNzCVMTTNqVssqJN
        dzPfHCLLhdjjLGRnmnmr
        GPhPfGWgggfslffPsVPGsqJMzLQJtBprwQJJGQwLpQrw
        ZNdmvbDDbNvHbmZCcJQwMmzMwWWQrrwttp
        bvdDNdnvNbnHDdnDHHRSbnqhqhWfjWFVTVhRVjfjFTfP
        hTThfWNCDRfsVCDhpgzgbpPZZwbnZQns
        GSjGGcCBGmdjdSlGBcmZwzJzpPpJzwPwQbzgPd
        BGmcrcStcMMMmrSLmSMCvFVRFDhfFhhNDWWTqFqTvf
        ZmjDTTbmqQCCQQSwvhsL
        FGVJPmPmtRVRsCvvRLwwhC
        JgdHJgmfbjzTpTMf
        fTbsVCsssgLNrfNrgm
        zQvzZlRvddvpNLpZrMNNLZ
        HLvWFHHlFQvzHnnlnvQqhzWvstBwbGVtstjGqjjwqGGCcwGq
        JNpNdzzdJhNnfNGBZLqZqlhvSZSG
        QswtcmmwwmTmwwcwZSLlZLDSvSvlBZQD
        FsVFBbFgFsPwtVBTwgTPcsmpzdNngfzfpCzJdzCJzNCndn
        qcvrLBppgpWWWgLcpzPfhNDqdzqwDDzwhV
        MZFjFnHFMHbMntMtnwStfddPhDffDfzDfS
        QmnjMZnlHjmnMGFnFlMmjlZWzLgsGgcrspBBLCBcgvgBRC
        sdfWHjZfrZrSPMCQ
        zqtWRDDDRMbrQJPQ
        zwhwzmqwzmFpWzvFqBmFvjNHlHfgVLBgdfVfNVjLsl
        lRlBTlvlZfhtbGBWtFBz
        cqCNjjqjrNrcNjwDqNPCVrSQStSWshFhtQhbQzGzmFCG
        HjPPzMcdNqjcNHMqPjdpgpZflfdgnTfdlvlJ
        VpwQJVRtHplnnwtppHhqWBCfVdNNPqPBPWsBDq
        jzLZCrvvrZjZvqNffvDNDcWDWd
        LTrZZLFZbgTzgjZZjFClJhTHTplQpmnQlpmpQR
        JGJnSWLGSpWHVHwGGJHpZdwPdTTPMdTMDdlzccPMPv
        gqrrmtbrbgggqgBtqmRSrFgNCzvMDvlMPDdddvzBcPMMMDBd
        gjrmRgmtRggFtqjbhgbjrtnJJHWLHQWZZLhZsLLGHhSL
        BtTDNggLRPdWQHqggg
        wrVpVVlCJVGMMJVdHWSdPSqqRwSQSP
        vCVrpvvGjlphBRmZBhmBhBND
        lqDcZGcSSqSqbDnccSLJgHgLRfnvvJRLmvWJ
        FVCFPChQzVhmsFBgddRgJBfdNfJdfv
        FzCpmTQzjQCThppTSttqDccMTDGcDG
        QCSGBGCrCsMBTCQwMGSfvvLNNnnVLDlNVNDdVdlr
        ZHtPffjWbqgtmnNdvljFnFhdVv
        JRWbmgmRJtmJMGGwSBBRRRfQ
        LqNrCfCQQhtgnPnc
        JWBrWrVlbWgbbtcb
        VwvTBprdrVJVNLNMNNqfqpjN
        bjVqdHrdqVHPsPNbqHbqNdjFGRwRGlttRtMtRtFFGMLHJw
        cfSpZnBZWQBZJlGRJJcwGMGL
        WWBhTMgDTZghVjgjssbrbddd
    """.trimIndent()
}
